#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-dlm
Version  : 1.1.6.1
Release  : 55
URL      : https://cran.r-project.org/src/contrib/dlm_1.1-6.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/dlm_1.1-6.1.tar.gz
Summary  : Bayesian and Likelihood Analysis of Dynamic Linear Models
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-dlm-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Kalman filtering and smoothing, and Bayesian
    analysis of Normal linear State Space models, also known as 
    Dynamic Linear Models.

%package lib
Summary: lib components for the R-dlm package.
Group: Libraries

%description lib
lib components for the R-dlm package.


%prep
%setup -q -n dlm
pushd ..
cp -a dlm buildavx2
popd
pushd ..
cp -a dlm buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727044390

%install
export SOURCE_DATE_EPOCH=1727044390
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/dlm/CITATION
/usr/lib64/R/library/dlm/DESCRIPTION
/usr/lib64/R/library/dlm/INDEX
/usr/lib64/R/library/dlm/Meta/Rd.rds
/usr/lib64/R/library/dlm/Meta/data.rds
/usr/lib64/R/library/dlm/Meta/features.rds
/usr/lib64/R/library/dlm/Meta/hsearch.rds
/usr/lib64/R/library/dlm/Meta/links.rds
/usr/lib64/R/library/dlm/Meta/nsInfo.rds
/usr/lib64/R/library/dlm/Meta/package.rds
/usr/lib64/R/library/dlm/Meta/vignette.rds
/usr/lib64/R/library/dlm/NAMESPACE
/usr/lib64/R/library/dlm/NEWS
/usr/lib64/R/library/dlm/R/dlm
/usr/lib64/R/library/dlm/R/dlm.rdb
/usr/lib64/R/library/dlm/R/dlm.rdx
/usr/lib64/R/library/dlm/data/NelPlo.rda
/usr/lib64/R/library/dlm/data/USecon.rda
/usr/lib64/R/library/dlm/doc/dlm.R
/usr/lib64/R/library/dlm/doc/dlm.Rnw
/usr/lib64/R/library/dlm/doc/dlm.pdf
/usr/lib64/R/library/dlm/doc/index.html
/usr/lib64/R/library/dlm/help/AnIndex
/usr/lib64/R/library/dlm/help/aliases.rds
/usr/lib64/R/library/dlm/help/dlm.rdb
/usr/lib64/R/library/dlm/help/dlm.rdx
/usr/lib64/R/library/dlm/help/paths.rds
/usr/lib64/R/library/dlm/html/00Index.html
/usr/lib64/R/library/dlm/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/dlm/libs/dlm.so
/V4/usr/lib64/R/library/dlm/libs/dlm.so
/usr/lib64/R/library/dlm/libs/dlm.so
